// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

// Injectors from container.go:

func InitializeApplication() *Application {
	config := initializeConfig()
	database := prepareDB(config)
	client := prepareStorage(config)
	limiter := setupRatelimiting(config)
	internalUninitializedApplication := &uninitializedApplication{
		config:      config,
		db:          database,
		s3client:    client,
		RateLimiter: limiter,
	}
	application := setupRouter(internalUninitializedApplication, config)
	return application
}

// container.go:

type uninitializedApplication Application
