name: Build and Release Binary

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build x86_64 Linux Binary
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Bundle binary
        run: |
          nix bundle .
          install -m755 -T hostling-arx hostling-x86_64-linux

      - uses: softprops/action-gh-release@v3
        with:
          files: hostling-x86_64-linux
