name: "Test Hostling"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@v14

      - name: Run Go tests
        run: nix develop --command go test ./...

      - name: Run NixOS Test
        run: nix flake check -L